version: "3.7"

services:
  mysql: 
    build: ./docker/mysql
  # volumes:
  #   - todo-mysql-data:/var/lib/mysql
  app:
    tty: true
    stdin_open: true
    build: ./docker/app
    links:
      - mysql
    ports:
      - 8080:8080
# volumes:
#   mvn-mysql-data:
